name: first workflow
on:
  push:
    branches: [main]
jobs:
  code_checkout:
    runs-on: ubuntu-latest
    steps:
      - name: codecheckout
      - run: actions/checkout@v4
  build:
    needs: code_checkout
    runs-on: ubuntu-latest
    steps:
      - run: echo" building the application packages"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo " testing the application    
